### ISSUE TITLE
Mouse cursor does not change when hovering pane separators

### ISSUE THREAD

**Issue by jimklimov** [kuthulux/gnome-connection-manager#10]
Follows up on one of the problems identified in #4 - that we do not have visual feedback that the mouse cursor is in the correct point where it can resize panes (sessions in split-view, server tree vs session view).

**Comment by kuthulux** [comment]
what gtk theme are you using?
does it happen in other programs? nautilus for instance?

**Comment by jimklimov** [comment]
Honestly, got no idea :) Something that comes by default with OI's MATE, I suppose.

**Comment by kuthulux** [comment]
I gave a go at openIA lice cd, and the default theme is the problem, it doesn't change the mouse pointer in any app. But if you change the theme to any other, it will work.

**Comment by jimklimov** [comment]
(I assume you meant OpenIndiana?) Curious, the cursor did change for window borders, so I thought the activity was enabled and possible in the WM... anyhow, going to Preferences/.../Appearance and picking any random theme (my original one was deemed "Custom" in that settings UI), including going back to Adwaita, did enable the cursor on split-lines. And also they are more tangible now. Thanks for nudging in the right direction!
