### ISSUE TITLE
New shortcuts for "Duplicate Tab" and "Reset Terminal and Clear Scrollback"

### ISSUE THREAD

**Issue by msmigiel** [kuthulux/gnome-connection-manager#14]
Operating System: RHEL 7.8
Program Version: GCM 1.2.0

Two shortcuts that I would be nice to have would be:

Duplicate Tab: Opens a new tab with the same server as the current tab.
Reset Terminal and Clear Scrollback: This would clear all text from the terminal, clear all scrollback, and leave the user with an empty prompt remaining. I find this useful if I want to clear everything quickly.

**Comment by kuthulux** [comment]
the shortcut for resetting terminal and scrollback already exists, you can find it in settings, shortcut as "reset", by default is ctrl+k, but i will change it to ctrl+shit+k by default.

i will add the other shortcut for duplicating the current tab.

**Comment by msmigiel** [comment]
Thank you - I did notice the Reset shortcut, however there are some issues with it:

1.) No matter what I cannot change the hotkey. Every time I do and come back, it is reset to CTRL+K.
2.) It does do as you say but I have to hit Enter to see the prompt. Would it be possible to show the prompt immediately after a reset?

**Comment by kuthulux** [comment]
1. after setting the hotkey, click outside the field, for instance, in the shortcut name, before clicking OK.
2. sorry, the VTE terminal works that way.

**Comment by msmigiel** [comment]
Thank you for the clarification - clicking off the field does work.

Is there any way to simulate an "Enter" press after clearing the screen to bring back the prompt? A minor issue but this would be one less keystroke for the end user. Maybe make this an optional flag in case someone doesn't want this?

**Comment by kuthulux** [comment]
it should be possible to send an "Enter" keypress, but it will be like a real press, so for instance if you write a command but you havent sent it yet, for instance "ls -l" , then after sending the enter it will execute the command.
so I prefer to leave as it is now, to prevent executing something by accident.
