### ISSUE TITLE
Unable to connect to AIX machines

### ISSUE THREAD

**Issue by msmigiel** [kuthulux/gnome-connection-manager#17]
Operating System: RHEL 7.8
Program Version: GCM 1.2.0

I am trying to access several AIX machines and am unable to from GCM. I've observed that if I create a connection and save the password, GCM hangs forever. If I do not put a password and I enter it upon initiating the connect, it works fine. Enabling logging does not add any extra information.

This seems specific to AIX as I have tried many RHEL and AIX machines and only the RHEL machines work.

**Comment by kuthulux** [comment]
hi @msmigiel,  can you paste a screenshot or copy/paste the text during a ssh session with AIX please.
I suspect the issue is because GCM waits for certain text to send the password to the server, and AIX may be using a different login prompt than most ssh servers, so GCM waits indefinitly.

**Comment by msmigiel** [comment]
Using Putty and manually entering the user and password gives the following. It doesn't seem to be any different than on my RHEL machines. Is there any special logging I can enable to see what is going on? I have a basic familiarly with Python and I can add some debug statements if you need.

login as: root
root@<ip>'s password:
Last unsuccessful login: Mon Apr 20 16:51:57 2020 on ssh from <ip>
Last login: Tue Apr 21 09:43:45 2020 on /dev/pts/0 from <ip>

/root >

**Comment by kuthulux** [comment]
can you try connecting from a terminal:
`ssh -l username server-ip`

it shouldn't asks for the username, just the password.

**Comment by msmigiel** [comment]
Doing that gives a similar output:

```
>ssh -l root <ip>
root@<ip>'s password: 
Last unsuccessful login: Mon Apr 20 16:51:57 2020 on ssh from <ip>
Last login: Tue Apr 21 09:54:19 2020 on /dev/pts/0 from <ip>

/root >
```

**Comment by kuthulux** [comment]
that's weird, maybe AIX doesn't like \r as newline
edit ssh.expect and append \n in line 44, so the line looks like this:
`$reg { send "$pass\r\n"; exec kill -WINCH [ pid ]; interact; }`

**Comment by msmigiel** [comment]
Thank you, that does work. Strangely, what I've noticed is that some of my AIX machines work fine without the change above and some need it. If it won't hurt other machine types then it might be good to add this fix just in case.

**Comment by kuthulux** [comment]
looks like using \n instead of \r doesn't have any side effects, in fact, the binary sshpass uses \n.
can you test that please, just \n instead of \r\n, with your AIX servers.

**Comment by msmigiel** [comment]
With only \n, things still work as they did before.

**Comment by jimklimov** [comment]
Maybe pass the `$pass\r`, then `expect` some output (some result of login), if it times out, pass `\n` additionally, expect/timeout again - and if either of that works (expect variables can be set to track either success and bail from the loop if a flag is set), then `exec` etc.
