### ISSUE TITLE
Ability to set application title

### ISSUE THREAD

**Issue by msmigiel** [kuthulux/gnome-connection-manager#19]
Operating System: RHEL 7.8
Program Version: GCM 1.2.0

It would be nice to have the ability to set the application title. For example, I would set it to something like "GCM - tab's name" so that I could see from the taskbar what connection I had open.

**Comment by msmigiel** [comment]
I took the latest build with this fix and it is mostly working except for a few things.

1.) The string "Gnome Connection Manager" comes first. I am running this through a VNC client with low resolution so that is all I see in my taskbar. I can manually modify the code to change app_name to something like "GCM" but would it be possible to have a UI option to change the app name in the title?
2.) There is a bug in which if you use a keyboard shortcut (in my case, ALT+# to change to that # tab), the app title does not update. It only updates when clicking with the mouse. 
3.) There is another bug in which if you close a tab, that tab's title stays in the app title despite focus changing to another open tab. It should update upon a tab's closure.

**Comment by kuthulux** [comment]
yeah, I forgot to include a callback for setting the title when swtinching using shortcuts.
With that commmit It should work right now.
Also I added the option to override the title string, so now you can set anything you want.

**Comment by msmigiel** [comment]
Thank you, those issues are now fixed. One minor thing, it seems that changing the title requires the application to restart. I'm not sure if this is unavoidable or not, but it might be something to document.

**Comment by kuthulux** [comment]
you dont have to restart for the new title to take effect, when opening/switching/clicking consoles it will show the new title.
