### ISSUE TITLE
With gcm-1.2.0 (WIP) the "Send commands after login" seems ignored

### ISSUE THREAD

**Issue by jimklimov** [kuthulux/gnome-connection-manager#2]
I had a configuration of remote hosts with version 1.1.0, which is still recognized after running the current Git HEAD as far as editing the hosts goes. However after initial log in to a host, the "Send commands..." are not in fact sent into the shell session.

**Comment by kuthulux** [comment]
thanks for the fix, vte is a little messy in the versions and deprecations area.
