### ISSUE TITLE
Feature request: is it possible to make URLs clickable?

### ISSUE THREAD

**Issue by ksowa** [kuthulux/gnome-connection-manager#26]
For instance, when you use Ubuntu Terminal, after running e.g. :

```
~$ curl -I google.com
Location: http://www.google.com/
```
you are able to click the URL and open it in your browser. 

Such feature would be very usable when working with e.g. Bitbucket repositories, as they return URLs to create pull requests.

Would it be possible to have something like that in GCM?

![screenshot-2020-04-30_13-45-39](https://user-images.githubusercontent.com/1027333/80706636-e78c5180-8ae8-11ea-82a4-6ebd8f168ba6.png)

**Comment by kuthulux** [comment]
Hi, yes, i think so, 
I will take a look at how gnome-terminal does it. It should'n be too hard.

**Comment by kuthulux** [comment]
closing issue.
NOTE: clickable urls only works if VTE is compiled with PCRE2 support, which should be no problem for recent vte versions. 
If PCRE2 is not available, then only OSC8 escape sequenes are supported.
To test them, paste this code in the console:
```
printf '\e]8;;http://example.com\e\\This is a link\e]8;;\e\\\n'
```

it should print [This is a link](http://example.com/)
