### ISSUE TITLE
"Copy selection to clipboard" not working

### ISSUE THREAD

**Issue by pstast** [kuthulux/gnome-connection-manager#27]
When I select a text in console, I see the following error:

```
Traceback (most recent call last):
  File "/usr/share/gnome-connection-manager/gnome_connection_manager.py", line 687, in on_terminal_selection
    self.terminal_copy(widget)
  File "/usr/share/gnome-connection-manager/gnome_connection_manager.py", line 1092, in terminal_copy
    terminal.copy_clipboard_format(Vte.Format.TEXT)
AttributeError: 'Terminal' object has no attribute 'copy_clipboard_format'
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
```

**Comment by kuthulux** [comment]
What version of the libvte, python and python3-gi packages do you have?
maybe you have the gtk.2 version?

Just to clarify, if you have python2 and gtk 2, you must use gcm v1.1.0

this repo's version is for python 3/gtk 3

**Comment by pstast** [comment]
I have older GTK and Python (Ubuntu 16.04).

That was a misunderstanding. README states that "Starting with version 1.2.0 it supports python3 and GTK 3". There should be metioned, that it supports **ONLY** python3 and GTK 3.

New version notification appeared, so I went to download new version and did not find information that older environment is not supported.

**Comment by kuthulux** [comment]
sorry about that, i will update the readme in the repository and the site to mention it.

You can still download the previous version from the site.
