### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by ericc-dream** [kuthulux/gnome-connection-manager#30]
Finally a new version of GCM \o/ which will work on Ubuntu 20.04 LTS 
The upgrade works without problem, and the application seems to work 
However, I face some little issues , so I will open several "ticket" to avoid confusion
May be all this "problem" come from the same issue, but when I installed the .deb all dependencies was satisfied

Transparency : look stupid, but it doesn't work anymore. The main advantage, for me, was to make the text in "blue" a little bit more readable. Because "dark blue" on "black", is difficult 

ericc

**Comment by ericc-dream** [comment]
Not sure to understand what you mean by "the version from the repo " 
I had installed the .deb , and now I downloaded it from git, and I have the same behaviour ! 
Transparency doesn't work 
Ubuntu 20.04 LTS -  Gnome 3.36.2 - on X11

**Comment by kuthulux** [comment]
I don't know if it's a bug in gnome-shell, mutter, or gtk, but transparency is working ok using Unity. In gnome-shell when you close the app and the confirmation dialog pops up you can see the transparency is working

![image](https://user-images.githubusercontent.com/54181744/84443129-0532f780-ac0d-11ea-82de-1d637efbeff5.png)

anyway, I have prepared a fix that is working in 20.04 using unity, gnome-shell with X11 and with wayland.
It's kind of a hack, to enable transparency in gnome-shell I have to set `window.set_app_paintable(True)` wich results in a fully transparent window (menus, tabs, toolbars become transparent too). To avoid this I have to connect the "draw" signal and draw the background of the window by hand, but in wayland this results in a big border around the window.

What I had to do for this to work in x11 and wayland without the extra border, was to paint the background of the elements that became transparent using the same color as the window but without the alpha channel.

I have created  the branch [transparency-fix](https://github.com/kuthulux/gnome-connection-manager/tree/transparency-fix) with this fix.

Let me know how it works for you.

**Comment by ericc-dream** [comment]
I believed that Unity and Gnome was the same now, but it's not the case apparently ! 
The "transparency-fix" works for me on Gnome-Desktop 
FYI, I'm also using "Tilix" as emulation Terminal and the transparency works fine but it's probably not written in Python 
I found that also :
[https://discourse.gnome.org/t/top-level-window-transparency-in-newer-versions-of-gtk/2210](url)
Don't know if it can help

**Comment by kuthulux** [comment]
Fix version 2.
This fix is less hackish than the previous one.

To have transparent widgets in gnome-shell the key is to have a transparent window, I don't know why but it doesn't work otherwise. But since I don't want the window to be transparent I'm setting the alpha channel to 0.999, so it looks opaque but in that way allows to have transparent widgets.

Your link pointed me in the right direction, the solution is this method which takes the current background color from the gtk theme and uses 0.999 alpha.

```
    def enable_window_transparency(self, window):
        #hack to allow transparent widgets inside a opaque window
        #the key is to set the alpha channel of the window's background color to 0.9999, in that way the window is opaque but still allows transparent children

        #remove previously addded css to get the background color from the current gtk theme
        if hasattr(window, "style_provider") and window.style_provider:
            Gtk.StyleContext.remove_provider_for_screen(
                Gdk.Screen.get_default(),
                window.style_provider
            )

        #get window background color
        context = window.get_style_context()
        color = context.get_background_color(Gtk.StateFlags.NORMAL)

        #set the background color to the same as the gtk theme, but with alpha 0.99999 (it looks opaque but allows to have transparent widgets)
        CSS = b"""
        window.background {
            background-color: rgba(%d, %d, %d, %f);
        }
        """ % (color.red*255, color.green*255, color.blue*255, 0.999999)

        window.style_provider = Gtk.CssProvider()
        window.style_provider.load_from_data(CSS)

        context.add_provider_for_screen(
            window.get_screen(),
            window.style_provider,
            Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION
        )
```

can you test again using the branch "transparency-fix" please

**Comment by ericc-dream** [comment]
Sorry, I couldn't do it during the week-end ! 
Downloaded this morning and works with since, no issue for me ! 
Thanks
