### ISSUE TITLE
TERM setting

### ISSUE THREAD

**Issue by ericc-dream** [kuthulux/gnome-connection-manager#32]
Hi 
A simple question : 
What is the purpose of the field "TERM" in the setting ?

**Comment by kuthulux** [comment]
that setting allows to override the env variable TERM which affects the terminal emulation. For some servers you have to use a different emulation for the console to work properly, although is not very common.

If not set, then xterm-256color will be used by default.

you can check the current value using: `echo $TERM`

**Comment by ericc-dream** [comment]
Ok, I see ! Thanks for the information
