### ISSUE TITLE
Warning seen when launching from the command line

### ISSUE THREAD

**Issue by ericc-dream** [kuthulux/gnome-connection-manager#34]
probably nothing, but still need to report 
When launching "gnome-connection-manager" from the command line :

> $ Invalid entry in configuration file: No option 'update-title' in section: 'options'
./gnome_connection_manager.py:1596: DeprecationWarning: Gtk.ImageMenuItem.set_image is deprecated
  menu.set_image(Gtk.Image.new_from_icon_name(Gtk.STOCK_DIRECTORY, Gtk.IconSize.MENU))
./gnome_connection_manager.py:1621: DeprecationWarning: Gtk.StyleContext.get_background_color is deprecated
  rgba = self.treeServers.get_style_context().get_background_color(Gtk.StateFlags.NORMAL)
./gnome_connection_manager.py:566: DeprecationWarning: Gtk.Widget.override_color is deprecated
  self.get_widget('txtSearch').override_color(Gtk.StateFlags.NORMAL, parse_color_rgba('darkgray'))

I have seen several other software throwing much more information than that 

Regards
ericc

**Comment by kuthulux** [comment]
nothing to worry about right now, 
gtk3 is deprecating many methods in favor of using css for styling widgets. 
It's in my TODO list to migrate the code to use CSS instead of setting styles directly, but is no too high in my priorities atm.
