### ISSUE TITLE
Not opening console  after vte update in archlinux

### ISSUE THREAD

**Issue by big4test4** [kuthulux/gnome-connection-manager#47]
after latest update of vte3 getting this error

"gnome_connection_manager.py:114959): VTE-CRITICAL **: 17:52:44.709: void vte_terminal_spawn_with_fds_async(VteTerminal*, VtePtyFlags, const char*, const char* const*, const char* const*, const int*, int, const int*, int, GSpawnFlags, GSpawnChildSetupFunc, gpointer, GDestroyNotify, int, GCancellable*, VteTerminalSpawnAsyncCallback, gpointer): assertion 'callback' failed"

**Comment by martintxoz** [comment]
The same here, in Debian Testing, with vte in version 0.62.0-1. I can fix it if I downgrade the packages libvte-2.91-0, libvte-2.91-common and gir1.2-vte-2.91 from 0.62.0-1 to 0.60.3-1 (using the packages stored at http://snapshot.debian.org/package/vte2.91/0.60.3-1/). Many thanks for the app!!

**Comment by Mjasnik** [comment]
I have made a patch that works in Manjaro (most likely in ArchLinux too). Hope this helps.

[gcm_fix_vte_does_not_open_47.patch.txt](https://github.com/kuthulux/gnome-connection-manager/files/5326222/gcm_fix_vte_does_not_open_47.patch.txt)

**Comment by big4test4** [comment]
the new update vte3 0.62.1-1 and vte-common 0.62.1-1 fixed the issue in archlinux
