### ISSUE TITLE
Not getting prompt to add key when using password authentication

### ISSUE THREAD

**Issue by big4test4** [kuthulux/gnome-connection-manager#48]
we are not getting the prompt to add key when we are adding a new server with password authentication, but when we use private key authentication it shows the prompt.

**Comment by importos** [comment]
in /usr/share/gnome-connection-manager/ssh.expect
in line 46 replace this :
          "Are you sure you want to continue connecting (yes/no)?" { send "yes\n"; exp_continue; }

by :

          -re "Are you sure you want to continue connecting (yes/no.*)?" { send "yes\n"; exp_continue; }

thanks

**Comment by majidshirazy** [comment]
> in /usr/share/gnome-connection-manager/ssh.expect
> in line 46 replace this :
> "Are you sure you want to continue connecting (yes/no)?" { send "yes\n"; exp_continue; }
> 
> by :
> 
> ```
>       -re "Are you sure you want to continue connecting (yes/no.*)?" { send "yes\n"; exp_continue; }
> ```
> 
> thanks

Well done
Problem solved
Thanks

**Comment by kuthulux** [comment]
fixed by 21661bd26914019d4094f8b166f808b76d9d0469
