### ISSUE TITLE
Scrollbar click moves to proportional point in console log, not a screen up

### ISSUE THREAD

**Issue by jimklimov** [kuthulux/gnome-connection-manager#50]
It is customary that a single click on a scrollbar scrolls up a screenful (or a bit less), however with GCM I often use large scrollback buffers to hold the stacktraces and system logs and whatnot, and find that a click "somewhere above the current position" in the bar can get me hundreds of lines away from the starting point, proportionally to position of that line in the scrollback buffer length, like if I dragged the scroll-pointer there.

Can it be changed to scroll in screenfuls by single clicks (and click+hold)? The proportional position like now is useful sometimes I guess, but could go to a doubleclick in the scrollbar.

**Comment by kuthulux** [comment]
right now it works the same as gnome-terminal, clicking on the scrollbar's background will scroll to that position, to scroll by "pages" you have to shift+click on the scrollbar.
