### ISSUE TITLE
Tab-scrolling seems to go same way regardless of mouse wheel spin

### ISSUE THREAD

**Issue by jimklimov** [kuthulux/gnome-connection-manager#62]
While looking what's new compared to existing official release, I took a look at the tab-scrolling feature. Looks cool, but for some reason on my system (OpenIndiana in VirtualBox) it scrolls tabs in the same order regardless of wheel going up or down. Other scrolls on the system honor that, and seems the new codebase in GCM tries to as well, but something does not fit together...

**Comment by jimklimov** [comment]
Some tracing and docs-digging showed that original code assumed a smooth GDK scroll event, and in my case it was not smooth so offsets were zero. PR with fix for the other case posted.

**Comment by Hakun1n** [comment]
@jimklimov Awesome, this makes my daily work much easier, thanks !!
