### ISSUE TITLE
Cannot run on Fedora 35. 

### ISSUE THREAD

**Issue by alansenairj** [kuthulux/gnome-connection-manager#73]
It cannot run using Fedora 35 Gnome 41. 

I can only make it run using  ./gnome_connection_manager.py

It cannot work using .RPM package. 

an 09 19:24:55 z390 gnome-shell[10225]: Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x561a25b72340] is on because it needs an allocation.
jan 09 19:24:55 z390 gnome-shell[10225]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x561a25919330] is on because it needs an allocation.
jan 09 19:24:55 z390 gnome-shell[10225]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x561a27ae46a0] is on because it needs an allocation.
jan 09 19:25:38 z390 systemd[2404]: Started dbus-:1.2-org.gnome.gedit@0.service.
jan 09 19:26:03 z390 systemd[2404]: dbus-:1.2-org.gnome.gedit@0.service: Consumed 1.145s CPU time.
jan 09 19:26:10 z390 systemd[2404]: Started dbus-:1.2-org.gnome.gedit@1.service.
jan 09 19:26:30 z390 systemd[2404]: dbus-:1.2-org.gnome.gedit@1.service: Consumed 2.947s CPU time.
jan 09 19:26:31 z390 systemd[2404]: Started dbus-:1.2-org.gnome.gedit@2.service.
jan 09 19:26:39 z390 systemd[2404]: dbus-:1.2-org.gnome.gedit@2.service: Consumed 1.042s CPU time.
jan 09 19:26:41 z390 systemd[2404]: Started dbus-:1.2-org.gnome.gedit@3.service.
jan 09 19:26:44 z390 systemd[2404]: dbus-:1.2-org.gnome.gedit@3.service: Consumed 1.016s CPU time.
jan 09 19:26:49 z390 systemd[2404]: Started dbus-:1.2-org.gnome.gedit@4.service.
jan 09 19:26:58 z390 systemd[2404]: dbus-:1.2-org.gnome.gedit@4.service: Consumed 2.075s CPU time.
jan 09 19:27:01 z390 systemd[2404]: Started dbus-:1.2-org.gnome.gedit@5.service.
jan 09 19:27:18 z390 systemd[2404]: Started dbus-:1.2-org.gnome.gedit@6.service.
jan 09 19:28:45 z390 systemd[2404]: Started Application launched by gnome-shell.
jan 09 19:28:45 z390 systemd[2404]: Started Application launched by gnome-shell.
jan 09 19:28:45 z390 systemd[2404]: Started cgroupify@app-gnome-firefox-19489.scope.service.
jan 09 19:30:51 z390 gnome-shell[19489]: ###!!! [Parent][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost
jan 09 19:30:51 z390 systemd[2404]: app-gnome-firefox-19489.scope: Consumed 14.540s CPU time.
jan 09 19:30:51 z390 systemd[2404]: Stopping cgroupify@app-gnome-firefox-19489.scope.service...
jan 09 19:30:51 z390 systemd[2404]: Stopped cgroupify@app-gnome-firefox-19489.scope.service.
jan 09 19:30:56 z390 systemd[2404]: Started Application launched by gnome-shell.
jan 09 19:30:56 z390 systemd[2404]: Started Application launched by gnome-shell.
jan 09 19:30:56 z390 gnome-connection-manager.desktop[20305]: /usr/share/gnome-connection-manager/gnome_connection_manager.py:1566: DeprecationWarning: Gtk.StyleContext.get_background_color is deprecated
jan 09 19:30:56 z390 gnome-connection-manager.desktop[20305]:   rgba = self.treeServers.get_style_context().get_background_color(Gtk.StateFlags.NORMAL)
jan 09 19:30:56 z390 gnome-connection-manager.desktop[20305]: /usr/share/gnome-connection-manager/gnome_connection_manager.py:868: DeprecationWarning: Gtk.ImageMenuItem.set_image is deprecated
jan 09 19:30:56 z390 gnome-connection-manager.desktop[20305]:   menuItem.set_image(Gtk.Image.new_from_icon_name(Gtk.STOCK_COPY, Gtk.IconSize.MENU))
jan 09 19:30:56 z390 python3[20305]: detected unhandled Python exception in '/usr/share/gnome-connection-manager/gnome_connection_manager.py'
jan 09 19:30:56 z390 gnome-connection-manager.desktop[20305]: Traceback (most recent call last):
jan 09 19:30:56 z390 gnome-connection-manager.desktop[20305]:   File "/usr/share/gnome-connection-manager/gnome_connection_manager.py", line 3390, in <module>
jan 09 19:30:56 z390 gnome-connection-manager.desktop[20305]:     main()
jan 09 19:30:56 z390 gnome-connection-manager.desktop[20305]:   File "/usr/share/gnome-connection-manager/gnome_connection_manager.py", line 3386, in main
jan 09 19:30:56 z390 gnome-connection-manager.desktop[20305]:     w_main = Wmain()
jan 09 19:30:56 z390 gnome-connection-manager.desktop[20305]:   File "/usr/share/gnome-connection-manager/gnome_connection_manager.py", line 460, in __init__
jan 09 19:30:56 z390 gnome-connection-manager.desktop[20305]:     provider.load_from_path(BASE_PATH + "/style.css")
jan 09 19:30:56 z390 gnome-connection-manager.desktop[20305]: gi.repository.GLib.GError: gtk-css-provider-error-quark: <broken file>:1:0Failed to import: Erro ao abrir arquivo /usr/share/gnome-connection-manager/style.css: Arquivo ou diretório inexistente (2)
jan 09 19:30:56 z390 abrt-server[20318]: Package 'gnome-connection-manager' isn't signed with proper key
jan 09 19:31:07 z390 systemd[2404]: Started Application launched by gnome-shell.
jan 09 19:31:07 z390 systemd[2404]: Started Application launched by gnome-shell.

**Comment by jimklimov** [comment]
Quite a bit of unrelated log noise, but the culprit is the missing
style.css - is in source, was not in recipe. A PR is open for that but
stalled :( As a quick fix, download a copy to your system ijto where other
shared data of the package goes.

**Comment by alansenairj** [comment]
oh yeah! it is so simple! thank you! 

Just to register this step if some one else need same help: 

cd /usr/share/gnome-connection-manager/
sudo vi style.css 
- paste this: 

  
notebook > header > tabs > tab box.selected {
    background-color: #EEEB00;
}



Just salve it and open the program!
