### ISSUE TITLE
Context menu lost with gcm-1.2.1+ (closer to current master) for disconnected sessions

### ISSUE THREAD

**Issue by jimklimov** [kuthulux/gnome-connection-manager#75]
I believe earlier versions allowed a disconnected session to be reconnected by right-clicking the gray tab and picking a menu option there. Now no context menu appears for SSH session - I have to close the gray tab and open a new session from scratch. It works for "Local" sessions though.

This is annoying me with the version I packaged earlier for OpenIndiana - recipe and patches at https://github.com/OpenIndiana/oi-userland/tree/oi/hipster/components/desktop/gnome2/gnome-connection-manager/patches and source corresponds to commit [d2ff66e3 ](https://github.com/kuthulux/gnome-connection-manager/commit/d2f66e3d668245f549ff6a69f662b1ebd669dc51) (still the current master HEAD as of this posting) plus the equivalent of PR #72

**Comment by yma-het** [comment]
Cannot reproduce
