### ISSUE TITLE
Clicking middle mouse button on a tab closes it instantly

### ISSUE THREAD

**Issue by jimklimov** [kuthulux/gnome-connection-manager#8]
While copy-pasting around in my session panes, more so when mixing the real mouse, laptop trackpad and buttons, and the keyboard shortcuts, I sometimes click the middle mouse button to paste while a cursor is over a tab I recently chose in the GCM GUI.

In such cases, the tab instantly disappears - without the usual "do you want to close the console" question (if configured to ask) - which is quite disruptive to the work being done ;)

**Comment by kuthulux** [comment]
Actually that was the intended behaviour, when you want a "fast way" to close a tab, just middle click it, avoiding the confirmation dialog.
Maybe the solution is to add another config option to enable confirmation on middle click.

**Comment by jimklimov** [comment]
Well, I haven't seen it documented anywhere, and as described - this behavior is a practical problem for pasting with the middle mouse button. I've lost a fair bit of work-in-progress due to that over the years.

**Comment by jimklimov** [comment]
Great, thanks! Adding the options seems easier than I thought :)
