### ISSUE TITLE
pass arguments to ssh

### ISSUE THREAD

**Issue by Danipiario** [kuthulux/gnome-connection-manager#85]
How can I pass extra arguments to ssh connection?
I try with "extra arguments" field filled with "-o StrictHostKeyChecking=no" but I can't establish a connection

**Comment by yma-het** [comment]
Please ping me in about a week, ill check it. I have no time now(

**Comment by jimklimov** [comment]
Strange, I've done just that (without quotes) and it worked. Needed the `-o` tojen part though.

**Comment by Danipiario** [comment]
Sorry, it was my fault. It's working
